svn:
  username: "tachyonsvyd"
  password: ""
  path: "/home/aboobacker/projects/interim-test-svn"
  verified_path: "/home/aboobacker/projects/interim-test-svn-verified"
pms:
  username: ""
  password: ""
